name: Build Lib

on:
  push:
    branches: [ "ino_dev" ]
  pull_request:
    branches: [ "ino_dev" ]
  workflow_dispatch:
    inputs:
      tags:
        description: "Build"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build with make
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: toasty
        path: src/toasty.h build/libtoasty.a
